#!/bin/sh
setOsPath=$(grub-mkrelpath /boot/gpu-power-prefs-x86_64.efi)
tail -n +7 $0|sed -e s#APPLE_SET_OS_PATH#$setOsPath#g
exit
# This script will load /boot/gpu-power-prefs-x86_64.efi from your root filesystem to allow usage of the iGPU on dual GPU macbooks.
# It should account for btrfs subvolumes and encryption, and probably lvm.
menuentry "Enable iGPU for future boots with gpu-power-prefs=1 and shutdown" --class tool {
	chainloader foo
	root_old=${root}
	root=(hd0)
	chainloader (${root_old})APPLE_SET_OS_PATH
	boot
}
